language: ruby
rvm:
  - 1.8.7
  - 1.9.3
gemfile:
  - Gemfile
  - Gemfile-rails4
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
matrix:
  exclude:
    - gemfile: Gemfile-rails4
      rvm: 1.8.7
  allow_failures:
    - { rvm: 1.8.7 }
