sudo: false
language: ruby
rvm:
  - 2.3.1
  - 2.2.0
gemfile:
  - Gemfile
  - Gemfile-sprockets2-sprocketsrails2
  - Gemfile-sprockets3-sprocketsrails2
  - Gemfile-rails41
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
